from .smart_color_match import NODE_CLASS_MAPPINGS as SCM_CLASS, NODE_DISPLAY_NAME_MAPPINGS as SCM_DISPLAY
from .cloth_texture_replace import NODE_CLASS_MAPPINGS as CTR_CLASS, NODE_DISPLAY_NAME_MAPPINGS as CTR_DISPLAY

NODE_CLASS_MAPPINGS = {**SCM_CLASS, **CTR_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**SCM_DISPLAY, **CTR_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']