from .smart_color_match import NODE_CLASS_MAPPINGS as SCM_CLASS, NODE_DISPLAY_NAME_MAPPINGS as SCM_DISPLAY

NODE_CLASS_MAPPINGS = {**SCM_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**SCM_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']